### ISSUE TITLE
Add Portuguese-Brazil (pt-BR) i18n version

### ISSUE THREAD

**Issue by dpedoneze** [tatey/delayed-web#25]
Default i18n file: 

```yml
pt-BR:
  delayed/web:
    views:
      id:
      job:
      jobs:
      status:
      created_at:
      run_at:
      attempts:
      last_error:
      server_time:
      handler:
      actions:
      current_queue:
      buttons:
        run_next:
        delete:
      queue:
        empty:
      errors:
        empty:
      statuses:
        executing:
        failed:
        queued:
      confirm:
        delete:
    flashes:
      jobs:
        queued:
          alert:
          notice:
        destroyed:
          alert:
          notice:

  time:
    formats:
      short:
```
